viogpu: Fix recursive includes
virtio-win/kvm-guest-drivers-windows pull request #1041
Opened 2024-02-13 23:06 UTC by davispuh

Currently there are several includes that cause recursive including - it still works because of include guards but it's not good idea for this to happen in first place and sometimes it can cause quite puzzling errors.

Some examples:
* helper.h -> viogpu_pci.h -> helper.h
* helper.h -> viogpu_idr.h -> helper.h

2024-02-14 08:28 UTC, vrozenfe approved these changes
Thanks.
Vadim.

2024-02-15 16:20 UTC, YanVugenfirer requested changes
I'm afraid I have to disagree on the ideological level with the change. If anything should be changed, then it is a virtio-related stuff that should be removed from the helper.h 
```
    #include "viogpu_pci.h"
     #include "viogpu_idr.h"
```
and added to viogpu.h. And then only virtiogpu.h to be included in the virtiopgu\graphics related headers.

2024-02-15 19:02 UTC, davispuh commented
I actually agree but that's larger change, I updated PR.

2024-02-21 07:27 UTC, YanVugenfirer approved these changes

2024-02-21 07:30 UTC, YanVugenfirer commented
rerun tests

2024-02-25 10:42 UTC, merged