RHEL-72207: Apply clang-formatt to ivshmem folder
virtio-win/kvm-guest-drivers-windows pull request #1236
Opened 2024-12-26 11:49 UTC by Jedoku

2024-12-26 11:54 UTC, YanVugenfirer approved these changes

2024-12-26 11:54 UTC, YanVugenfirer commented
@Jedoku The PR has conflicts. Otherwise +1

2024-12-26 12:00 UTC, YanVugenfirer approved these changes

2024-12-26 13:37 UTC, kostyanf14 requested changes

2024-12-26 13:37 UTC, kostyanf14 commented on ivshmem/Device.c
>  #else
@YanVugenfirer 

Looks like a part for refactoring. This condition can be removed as we drop Win8 support.

2024-12-26 13:37 UTC, kostyanf14 commented on ivshmem/Device.c
> +                DEBUG_INFO("%s", "This driver does not support > 64 interrupts, they will be ignored in the ISR.");
Why without brackets?

2024-12-26 13:37 UTC, kostyanf14 commented on ivshmem/Queue.c
>          return STATUS_DEVICE_ALREADY_ATTACHED;
brackets?

2024-12-26 13:37 UTC, kostyanf14 commented on ivshmem/test/ivshmem-test.cpp
> +
brackets?

2024-12-26 13:42 UTC, kostyanf14 commented on ivshmem/Device.c
>  #else
@Jedoku ignore this comment

2024-12-26 13:51 UTC, kostyanf14 commented
s/clang-formatt/clang-format/

2024-12-28 20:33 UTC, YanVugenfirer approved these changes

2024-12-30 10:30 UTC, YanVugenfirer approved these changes

2024-12-30 10:32 UTC, YanVugenfirer approved these changes

2024-12-30 10:35 UTC, kostyanf14 approved these changes

2024-12-30 10:36 UTC, merged