RHEL-69079: Apply clang-format for vioserial folder
virtio-win/kvm-guest-drivers-windows pull request #1239
Opened 2024-12-30 15:58 UTC by Jedoku

2024-12-31 08:28 UTC, YanVugenfirer commented on vioserial/app/main.cpp
> +        while (getchar() != '\n')
Why? Looks strange.

2024-12-31 11:06 UTC, YanVugenfirer commented on vioserial/app/main.cpp
> +        while (getchar() != '\n')
The ";" should be one the same line with "while" in my opinion.

2024-12-31 11:58 UTC, YanVugenfirer requested changes

2024-12-31 11:58 UTC, YanVugenfirer commented on vioserial/libtestsvc/utils.cpp
> +                                                                                                     "The service "
This looks strange. No need for so much indentation and braking the strings

2024-12-31 11:58 UTC, YanVugenfirer commented on vioserial/sys/public.h
> +            0x4237,
Let's check if we can not to break GUIDs. BTW: doesn't it fit 100 chars line?

2025-01-08 17:16 UTC, Jedoku commented on vioserial/sys/public.h
> +            0x4237,
it has 125/120 chars line

2025-01-09 11:11 UTC, YanVugenfirer approved these changes

2025-01-09 11:11 UTC, kostyanf14 approved these changes

2025-01-13 08:04 UTC, YanVugenfirer commented on vioserial/app/main.cpp
> +        while (getchar() != '\n');
Don't change now, but let's try:
_AllowShortLoopsOnASingleLine: true
AllowShortBlocksOnASingleLine: true_

2025-01-13 08:04 UTC, YanVugenfirer commented on vioserial/libtestapp/main.cpp
> +        while (getchar() != 'q');
Don't change now, but let's try:
_AllowShortLoopsOnASingleLine: true
AllowShortBlocksOnASingleLine: true_

2025-01-13 08:06 UTC, YanVugenfirer approved these changes

2025-01-13 08:06 UTC, merged