Add Active Directory support
virtio-win/kvm-guest-drivers-windows pull request #792
Opened 2022-07-11 17:12 UTC by Daniel-Trevitz

For virtio-fs to work with an Active Directory connected system, we can't use NetUserGetInfo. Instead, use WTSQueryUserToken to get a token for the security context of the logged-in user, and then query the user and group SID. Use the SID to get the UID using WinFSP's preexisting mapping, which for standard users is just the previously used 0x30000+RID.

2022-07-11 17:14 UTC, Daniel-Trevitz commented
So far I have only tested this change on Windows 10 on the same VM as both an AD user and a standard user.

2022-07-12 06:30 UTC, YanVugenfirer commented
@Daniel-Trevitz Thanks a lot!
It was one of the pending issues together with case sensitivity support.

We are working to integrate WinFSP tests as part of CI, but it is still in progress. Can  you please run the tests and publish results here as well? https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#winfsp-tests

Best regards,
Yan.

2022-07-12 06:41 UTC, YanVugenfirer commented
@Daniel-Trevitz,
 
Sorry for going after formalities.
But can you please add "Signed-off-by" in commits? (can be done by "git commit -s --amend" and then force pushing to you branch).
Should be: "Signed-off-by: Name Family <youremail@domain.com>"

2022-07-12 08:00 UTC, kostyanf14 commented
Hi @Daniel-Trevitz,

VirtIO FS build failed. We use EWDK Build Env to build all drivers in CI, not a Visual Studio Dev Env. Please check logs, perform fixes and update your PR.

2022-07-12 08:01 UTC, kostyanf14 requested changes
Build failed in EWDK env.

2022-07-12 08:02 UTC, YanVugenfirer commented
```
Build FAILED.

       "C:\workspace\VirtIO-EWDK\virtio-win.sln" (Build target) (1) ->
       "C:\workspace\VirtIO-EWDK\viofs\svc\virtiofs.vcxproj" (default target) (14) ->
       (ClCompile target) -> 
         C:\workspace\VirtIO-EWDK\viofs\svc\virtiofs.cpp(642,19): warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data [C:\workspace\VirtIO-EWDK\viofs\svc\virtiofs.vcxproj]


       "C:\workspace\VirtIO-EWDK\virtio-win.sln" (Build target) (1) ->
       "C:\workspace\VirtIO-EWDK\viofs\svc\virtiofs.vcxproj" (default target) (14) ->
       (ClCompile target) -> 
         C:\workspace\VirtIO-EWDK\viofs\svc\virtiofs.cpp(2721): error C4700: uninitialized local variable 'hideStuff' used [C:\workspace\VirtIO-EWDK\viofs\svc\virtiofs.vcxproj]

    1 Warning(s)
    1 Error(s)
```

2022-07-12 08:38 UTC, YanVugenfirer commented
If not too much trouble, I would prefer to have two PRs.

2022-07-12 09:50 UTC, Daniel-Trevitz commented
Weird... I'm using EWDK...

2022-07-12 09:58 UTC, Daniel-Trevitz commented
> If not too much trouble, I would prefer to have two PRs.

Me too, why did it change my PR??? I'll try to rebase, fix the build error, and try again.

2022-07-12 10:06 UTC, Daniel-Trevitz commented
> > If not too much trouble, I would prefer to have two PRs.
> 
> Me too, why did it change my PR??? I'll try to rebase, fix the build error, and try again.

Simple; the PR is merging branches not commits. As for the build error, I am using EWDK, but I uploaded and old copy with github's direct editor.

2022-07-12 10:53 UTC, Daniel-Trevitz commented
> @Daniel-Trevitz Thanks a lot! It was one of the pending issues together with case sensitivity support.
> 
> We are working to integrate WinFSP tests as part of CI, but it is still in progress. Can you please run the tests and publish results here as well? https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#winfsp-tests
> 
> Best regards, Yan.

@YanVugenfirer, I compiled the tests with EWDK with msbuild build\VStudio\testing\winfsp-tests.vcxproj /P:Platform=x64
Then ran the specified command, but there was no output.

2022-07-12 10:56 UTC, Daniel-Trevitz commented
Creating new PR to use new branch

2022-07-12 10:56 UTC, closed without merging

2022-07-12 11:25 UTC, YanVugenfirer commented
> > @Daniel-Trevitz Thanks a lot! It was one of the pending issues together with case sensitivity support.
> > We are working to integrate WinFSP tests as part of CI, but it is still in progress. Can you please run the tests and publish results here as well? https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/VirtIO-FS:-Shared-file-system#winfsp-tests
> > Best regards, Yan.
> 
> @YanVugenfirer, I compiled the tests with EWDK with msbuild build\VStudio\testing\winfsp-tests.vcxproj /P:Platform=x64 Then ran the specified command, but there was no output.

@viktor-prutyanov Can you please take a look?

2022-07-12 11:41 UTC, viktor-prutyanov requested changes
Hi @Daniel-Trevitz,

Thank you for the PR!

I've fetched it and tried to test on a system with no Active Directory users. All experiments were made with the same user. Here is what I found:
1. When running FS as a Windows service, all manual manipulations seems to work. I've also run winfsp-tests and fsbench and there are no regressions found.
2. When running FS as a console program, I can't delete existing files/folders and can't create new ones. Explorer says "You require permissions from S-1-5-0". It looks like a significant regression.

2022-07-12 11:43 UTC, Daniel-Trevitz commented
@viktor-prutyanov, Are run running it from console as an admin user?

2022-07-12 11:44 UTC, viktor-prutyanov commented
@YanVugenfirer As for me, I run winfsp-tests from WinFsp installation

2022-07-12 11:44 UTC, Daniel-Trevitz commented
> @YanVugenfirer As for me, I run winfsp-tests from WinFsp installation

They are in there? Where????

2022-07-12 11:52 UTC, viktor-prutyanov commented
> Are you running it from console as an admin user?

C:\Users\Administrator>whoami /user

User Name                     SID
============================= ============================================
win-1ctat4f52f9\administrator S-1-5-21-3033090981-1282011401-371400141-500

2022-07-12 11:54 UTC, viktor-prutyanov commented
> They are in there? Where????

Something like `C:\Program Files (x86)\WinFsp\bin\winfsp-tests-x64.exe`

2022-07-12 11:57 UTC, Daniel-Trevitz commented
@viktor-prutyanov 

Is this what you're seeing?

```

2022-07-12 12:03 UTC, Daniel-Trevitz commented
Well. RTFM...

Obtains the primary access token of the logged-on user specified by the session ID. To call this function successfully, the calling application **must be running within the context of the [LocalSystem account](https://docs.microsoft.com/en-us/windows/desktop/Services/localsystem-account)** and have the SE_TCB_NAME privilege.

2022-07-12 12:05 UTC, Daniel-Trevitz commented
> > Are you running it from console as an admin user?
> 
> C:\Users\Administrator>whoami /user
> 
> User Name SID ============================= ============================================ win-1ctat4f52f9\administrator S-1-5-21-3033090981-1282011401-371400141-500

@viktor-prutyanov, Okay. I can't work on this anymore till tonight. Seems that the solution is to use OpenProcessToken when not the LocalSystem account. In that case AD users will not function correctly, but the previous use cases should still work.