Update Readme to point a latest build steps
virtio-win/kvm-guest-drivers-windows pull request #856
Opened 2022-11-11 20:38 UTC by asbalderson

Current drivers are built using EWDK 11, have the readme point to that build process.

2022-11-12 17:58 UTC, YanVugenfirer requested changes
Please add "Signed-off-by:" at the end of your commit.

For example: Alexander Balderson <alexander@yourdomain.com>

Thanks,
Yan.

2022-11-14 17:24 UTC, asbalderson commented
@YanVugenfirer should be good now

2022-11-15 07:47 UTC, YanVugenfirer commented
> @YanVugenfirer should be good now

Hi Alexander,

Sorry for the confusion, the "Signed-off" part should be in the commit message. It is not mandatory in the PR description. 
The repository only have commits with their messages, PRs and discussions are meta-data of github and are not saved in the repository.

Best regards,
Yan.

2022-11-17 08:34 UTC, YanVugenfirer approved these changes

2022-11-17 08:34 UTC, merged