viofs: add -F option
virtio-win/kvm-guest-drivers-windows pull request #920
Opened 2023-06-03 15:30 UTC by EDI-Systems

Windows has a restriction that the filesystem name must be "NTFS" to run program with admin privilege from it.

Add -F option and allow viofs to masquerade itself as any filesystem (e.g. NTFS) so the Windows restriction is lifted and we may run lots of useful tools and perform software installs from it.

WinFsp's devels are aware of it and in their example memfs they did it this way. The following is an excerpt from their FAQ.

https://winfsp.dev/doc/Frequently-Asked-Questions/

2. I cannot run a program located in a WinFsp drive as administrator. I cannot run regedit.exe from within a WinFsp drive.

When running an executable as administrator, the Windows OS seems to require that the name of the file system that is housing the executable is "NTFS". For example, the MEMFS file system with the command line memfs-x64.exe -i -F NTFS -m X: works.

2023-06-03 15:31 UTC, EDI-Systems commented
The -F option is optional. When not designated it falls back to the default VirtIO-FS.

2023-06-05 18:11 UTC, viktor-prutyanov commented
> Windows OS seems to require that the name of the file system that is housing the executable is "NTFS"

But how executables are running from FAT32?

2023-06-09 08:44 UTC, EDI-Systems commented
> > Windows OS seems to require that the name of the file system that is housing the executable is "NTFS"
> 
> But how executables are running from FAT32?

NTFS and FAT32 (and even samba-mounted anything), all these windows built-ins are fine. but others are not allowed to pass this check, I guess cause windows haven't seen them. WinFsp already pointed this out.

2023-06-09 09:09 UTC, EDI-Systems commented
> > > > Windows OS seems to require that the name of the file system that is housing the executable is "NTFS"
> > > 
> > > 
> > > But how executables are running from FAT32?
> > 
> > 
> > NTFS and FAT32 (and exFAT, or even SAMBA-mounted anything), all these Windows built-in filesystems are fine. but others are not allowed to pass this check, I guess cause they are alien to Windows. WinFsp devs already pointed this out. I tried and the original doesn't allow (as it gives VirtIO-FS filesystem name), but this modified version I'm currently using (which assimilates the WinFsp example MEMFS's solution) allows to run exe with admin.
> 
> So, if you pass -F FAT32, does it also work?

Yes it works, I can run AS SSD benchmark / CPU-Z / EVGA OC installer, etc. from it.

2023-06-09 09:18 UTC, EDI-Systems commented
> > > > > Windows OS seems to require that the name of the file system that is housing the executable is "NTFS"
> > > > 
> > > > 
> > > > But how executables are running from FAT32?
> > > 
> > > 
> > > NTFS and FAT32 (and exFAT, or even SAMBA-mounted anything), all these Windows built-in filesystems are fine. but others are not allowed to pass this check, I guess cause they are alien to Windows. WinFsp devs already pointed this out. I tried and the original doesn't allow (as it gives VirtIO-FS filesystem name), but this modified version I'm currently using (which assimilates the WinFsp example MEMFS's solution) allows to run exe with admin.
> > 
> > 
> > So, if you pass -F FAT32, does it also work?
> 
> Yes it works, I can run AS SSD benchmark / CPU-Z / EVGA OC installer, etc. from it.

Now I have a 24TB "FAT32" disk.............

2023-06-09 13:19 UTC, YanVugenfirer commented
Hi @EDI-Systems , please add "sign-off" according to the contribution guidelines with your real name: https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/contributing.md

Optional: if you can comment on your use case here: https://github.com/virtio-win/kvm-guest-drivers-windows/discussions/726

Thanks,
Yan.

2023-06-09 14:42 UTC, EDI-Systems commented
> Hi @EDI-Systems , please add "sign-off" according to the contribution guidelines with your real name: https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/contributing.md
> 
> Optional: if you can comment on your use case here: #726
> 
> Thanks, Yan.

Done.

2023-06-13 14:57 UTC, YanVugenfirer approved these changes

2023-06-14 07:37 UTC, viktor-prutyanov requested changes
Hi @EDI-Systems 

I suggest you to add a couple of minor changes and then we can merge the PR.

2023-06-14 07:37 UTC, viktor-prutyanov commented on viofs/svc/virtiofs.cpp
> +    VIRTFS(ULONG DebugFlags, bool CaseInsensitive,
Trailing whitespace:
```suggestion
    VIRTFS(ULONG DebugFlags, bool CaseInsensitive,
```

2023-06-14 07:37 UTC, viktor-prutyanov commented on viofs/svc/virtiofs.cpp
> +        sizeof(VolumeParams.FileSystemName) / sizeof(WCHAR),
Trailing whitespace:
```suggestion
        sizeof(VolumeParams.FileSystemName) / sizeof(WCHAR),
```

2023-06-14 07:37 UTC, viktor-prutyanov commented on viofs/svc/virtiofs.cpp
> +        "    -F FileSystemName   [pretend to be another file system - NTFS]\n"
```suggestion
        "    -F FileSystemName   [file system name for OS]\n"
```

2023-06-15 08:58 UTC, viktor-prutyanov commented
Hi @EDI-Systems 

Could you please squash all the commits into the first one?

2023-06-15 17:03 UTC, EDI-Systems commented
> Hi @EDI-Systems
> 
> Could you please squash all the commits into the first one?

squashed and pushed.

2023-06-16 05:10 UTC, viktor-prutyanov approved these changes

2023-06-16 06:36 UTC, YanVugenfirer approved these changes

2023-06-16 06:37 UTC, YanVugenfirer commented
@EDI-Systems Thank you for the PR, I am waiting for CI to finish before merging. We have a large queue due to other PRs that touched virtio library code.

2023-06-18 07:28 UTC, merged

2023-06-18 07:28 UTC, YanVugenfirer commented
@EDI-Systems Thanks a lot! Merging.

@viktor-prutyanov Please update the WiKi.

2023-06-20 10:09 UTC, viktor-prutyanov commented
> Please update the WiKi.

@YanVugenfirer Updated.